name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v5
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: --snapshot --skip publish --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: List files in the repository
      run: |
          ls dist/
          ls dist/packwiz-build_linux_amd64_v1

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux 64-bit x86
        path: dist/packwiz-build_linux_amd64_v1/